[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['cd server && npm install']

[phases.build]
cmds = ['echo "No build step needed for backend"']

[start]
cmd = 'cd server && npm start'
